spring.application.name=ms-notification

server.port=8082

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=25
spring.mail.username=7b9a65b618d368
spring.mail.password=98b83dfe41d971
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true